### ISSUE TITLE
Please consider adding a license to your repository

### ISSUE THREAD

**Issue by dasblinkenlight** [Jaimecclin/cvs-pluging-vscode-ext#2]
I am going through the process of recommending your plugin for use at my work. As part of this process I must specify the type of the license (MIT, BSD, GPL, etc.) for our legal department to approve the use of the plugin, even though it's listed as free. If possible, could you please assign a license to your repository?

**Comment by Jaimecclin** [comment]
Sorry, it seems I totally missed this thread. I'm glad you like it and thanks for your suggestion. I will do it this week.

**Comment by Jaimecclin** [comment]
Hi [dasblinkenlight](https://github.com/dasblinkenlight)

Not quite sure which one I should select. But I added. Hope it's helpful. :)

Cheers!
