### ISSUE TITLE
Add revert file option

### ISSUE THREAD

**Issue by SICOPOLY** [Jaimecclin/cvs-pluging-vscode-ext#3]
Could you add revert file option?
I think this will be usefull...
Here you have an example of how to do it
cvs update -r "BASE" -C -l -d -P "filename"

**Comment by Jaimecclin** [comment]
Hi [SICOPOLY](https://github.com/SICOPOLY)
Very busy a while ago. Completely missed this thread. Let me try it first. Give you feedback soon.

**Comment by Jaimecclin** [comment]
Hi @SICOPOLY 
Not sure if you are still a user or not. Just tell you the revert function is ready. Please update this extension!
