### ISSUE TITLE
Revision number in cvs diff 

### ISSUE THREAD

**Issue by bkarlsbrun** [Jaimecclin/cvs-pluging-vscode-ext#4]
Hi. I'm in the process of upgrading tools in our company. As we work with CVS I found your plugin very useful. Is it possible to add revision number of the file in repository in diff instead of using hardcoded 'head' ? It helps a lot during reviews when fixing some reopened old bugs.
Thanks!

**Comment by Jaimecclin** [comment]
Hi,
I'm glad you like it. About your suggestion, I like it and it's a doable functionality. But I'm not sure of the proper way to use the revision number on UI, such as an input box. Do you have any good ideas?

Cheers

**Comment by bkarlsbrun** [comment]
Hi,
Thanks for the fast reply!

The most primitive idea I got is :
After displaying all modified files and choosing one of them - run the
following from shell :
*cvs log current_file.cpp | grep revision*
the result in stdout  is :







*total revisions: 6;     selected revisions: 6revision 1.6revision
1.5revision 1.4revision 1.3revision 1.2revision 1.1*

Let's say we can choose 10 upper lines (not including : *total revisions:
6;     selected revisions: 6) *
and display them in the drop down menu.
so user can choose one of them - something like on the attachment (sorry I
definitely no UI/UX designer ).
Click on revision will activate same procedure as today, but based on
chosen revision

Will be glad to work with you on this issue
My direct email : ***@***.***

Thanks,
Baruch Karlsbrun

**Comment by Jaimecclin** [comment]
A Great idea. Better than mine. Let's do it this way!

**Comment by bkarlsbrun** [comment]
Hi

Great! How can I help you to push this forward?

**Comment by Jaimecclin** [comment]
Well, the requirement is clear. So just wait for a while.

**Comment by bkarlsbrun** [comment]
Ok, thank you.

**Comment by Jaimecclin** [comment]
Hi @bkarlsbrun 

I've pushed the new version. Please update the new extension. Is it ok if you can try and report to me? Thanks.

**Comment by bkarlsbrun** [comment]
Hi
Thank you!!!
It works for me.

Baruch

**Comment by Jaimecclin** [comment]
Great!
